services:
  - type: web
    name: lotr-rag
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.12.0"
